# Generated by Django 6.0.2 on 2026-02-16 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0004_specificationtype_productspecification'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productspecification',
            options={'ordering': ['spec_type__name'], 'verbose_name': 'элемент характеристик', 'verbose_name_plural': 'Характеристики товаров'},
        ),
        migrations.AlterModelOptions(
            name='stock',
            options={'verbose_name': 'запись остатков', 'verbose_name_plural': 'Остатки'},
        ),
    ]
