# Generated by Django 4.2.20 on 2026-02-26 19:32

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0005_alter_productspecification_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'ordering': ['-id'], 'verbose_name': 'Товар', 'verbose_name_plural': 'Товары'},
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(blank=True, validators=[django.core.validators.MinLengthValidator(10, message='Комментарий должен содержать не менее 10 символов'), django.core.validators.MaxLengthValidator(2000, message='Комментарий не должен превышать 2000 символов')], verbose_name='Комментарий'),
        ),
    ]
