# Generated by Django 4.2.20 on 2026-02-26 19:52

import appx.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('index', '0006_alter_product_options_alter_review_comment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='banner',
            name='image',
            field=models.ImageField(upload_to='banners/', validators=[appx.validators.banner_image_validator], verbose_name='Изображение'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to='products/gallery/', validators=[appx.validators.product_image_validator], verbose_name='Доп. изображение'),
        ),
    ]
