# Generated by Django 4.2.20 on 2026-02-28 02:24

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('index', '0007_alter_banner_image_alter_productimage_image'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='review',
            options={'ordering': ['-created_at'], 'verbose_name': 'Отзыв', 'verbose_name_plural': 'Отзывы'},
        ),
        migrations.AddField(
            model_name='review',
            name='is_verified_purchase',
            field=models.BooleanField(default=False, verbose_name='Проверенная покупка'),
        ),
        migrations.AddField(
            model_name='review',
            name='tags',
            field=models.JSONField(blank=True, default=list, verbose_name='Теги'),
        ),
        migrations.AddField(
            model_name='review',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='Обновлен'),
        ),
        migrations.AddField(
            model_name='review',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь'),
        ),
        migrations.AlterField(
            model_name='review',
            name='comment',
            field=models.TextField(validators=[django.core.validators.MinLengthValidator(10, message='Комментарий должен содержать не менее 10 символов'), django.core.validators.MaxLengthValidator(2000, message='Комментарий не должен превышать 2000 символов')], verbose_name='Комментарий'),
        ),
        migrations.AlterField(
            model_name='review',
            name='rating',
            field=models.PositiveSmallIntegerField(choices=[(1, '1 ★'), (2, '2 ★★'), (3, '3 ★★★'), (4, '4 ★★★★'), (5, '5 ★★★★★')], verbose_name='Оценка'),
        ),
        migrations.AddIndex(
            model_name='review',
            index=models.Index(fields=['product', '-created_at'], name='index_revie_product_555c46_idx'),
        ),
    ]
